wip: no gen
Signed-off-by: Sarah Funkhouser <147884153+golanglemonade@users.noreply.github.com>

diff --git a/fga/Taskfile.yaml b/fga/Taskfile.yaml
--- a/fga/Taskfile.yaml
+++ b/fga/Taskfile.yaml
@@ -11,16 +11,34 @@ tasks:
   create:
     desc: creates a new fga store with the testdata model
     cmds:
-      - fga store create --name "core dev" --model model/model.fga --api-token={{ .FGA_API_TOKEN }}
+      - fga store create --name "core dev" --model model/fga.mod --api-token={{ .FGA_API_TOKEN }}
+
+  generate:
+    desc: generates the organization level crud definitions based on the schema
+    dir: ../
+    cmds:
+      - go run fga/generate/main.go
+
+  validate:
+    desc: validates the fga model file
+    silent: true
+    cmds:
+      - |
+        result=$(fga model validate --file model/fga.mod)
+        if [ "$(echo "$result" | jq .is_valid)" != "true" ]; then
+          echo "Model validation failed:"
+          echo "$result" | jq .error
+          exit 1
+        fi
 
   test:
     desc: runs the fga model tests
     cmds:
+      - task: validate
       - fga model test --tests tests/tests.yaml
 
   tuple:write:
     desc: writes test tuples to the fga store
-    dir:
     vars:
       TUPLES:
         sh: find tests/tuples -type f -name '*.yaml' -print
